version: '3.9'
services:
  solr:
    build:
      context: ./
      dockerfile: ./deploy/images/solr.Dockerfile
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - catalog_core
      - /catalog-solr-conf
    image: comses/catalog/solr:6.6
    volumes:
      - solr:/opt/solr/server/solr/mycores
  redis:
    image: redis:latest
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./deploy/elasticsearch.conf.d/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./deploy/elasticsearch.conf.d/elasticsearch-dev.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
  db:
    image: postgres:14
    volumes:
      - ./docker/shared/pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD_FILE: /run/secrets/catalog_db_password
      POSTGRES_DB: comses_catalog
  django:
    volumes:
      - solr:/etc/solr/mycores/
      - ./docker/shared:/shared
    environment:
      DJANGO_SETTINGS_MODULE: 'catalog.settings.prod'
      LANG: "C.UTF-8"
      DB_USER: catalog
      DB_HOST: db
      DB_NAME: comses_catalog
      DB_PORT: 5432
      SOLR_HOST: solr
      SOLR_PORT: 8983
      SOLR_CORE_NAME: catalog_core
    depends_on:
      - db
      - redis
      - elasticsearch
      - solr
volumes:
  solr:
    driver: local
  esdata:
    driver: local
  data:
    driver: local
  static:
    driver: local
