# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 20:46
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='message',
            field=models.CharField(blank=True, max_length=2000)
        )
    ]
