# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:37
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Publication = apps.get_model('citation', 'Publication')
    Publication.objects.filter(status__in=('NEEDS_AUTHOR_REVIEW', 'COMPLETE')).update(status='REVIEWED')

def backwards(apps, schema_editor):
    Publication = apps.get_model('citation', 'Publication')
    Publication.objects.filter(status='REVIEWED', code_archive_url='').update(status='NEEDS_AUTHOR_REVIEW')
    Publication.objects.filter(status='REVIEWED').exclude(code_archive_url='').update(status='COMPLETE')


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0006_add_author_correspondence'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
