# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='from_citation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='resource_type',
            field=models.CharField(choices=[(b'JOURNAL_ARTICLE', 'Journal Article')], default=b'JOURNAL_ARTICLE', max_length=127),
        ),
    ]
