# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 20:36
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            'journalarticle',
            'journal',
            'tmp_journal'
        ),
        migrations.RenameField(
            'journalarticle',
            'pages',
            'tmp_pages'
        ),
        migrations.RenameField(
            'journalarticle',
            'issn',
            'tmp_issn'
        ),
        migrations.RenameField(
            'journalarticle',
            'volume',
            'tmp_volume'
        ),
        migrations.RenameField(
            'journalarticle',
            'issue',
            'tmp_issue'
        ),
        migrations.RenameField(
            'journalarticle',
            'series',
            'tmp_series'
        ),
        migrations.RenameField(
            'journalarticle',
            'series_title',
            'tmp_series_title'
        ),
        migrations.RenameField(
            'journalarticle',
            'series_text',
            'tmp_series_text'
        ),
        migrations.RenameField(
            'journalarticle',
            'doi',
            'tmp_doi'
        ),
        migrations.AddField(
            'publication',
            'resource_type',
            models.CharField(default='Journal Article', max_length=255)
        ),
        migrations.AddField(
            'publication',
            'is_primary',
            models.BooleanField(default=True)
        ),
        migrations.AddField(
            'publication',
            'journal',
            models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='core.Journal')
        ),
        migrations.AddField(
            'publication',
            'doi',
            models.CharField(blank=True, default='', max_length=255)
        ),
        migrations.AddField(
            'publication',
            'series_text',
            models.CharField(blank=True, default='', max_length=255)
        ),
        migrations.AddField(
            'publication',
            'series_title',
            models.CharField(blank=True, default='', max_length=255)
        ),
        migrations.AddField(
            'publication',
            'series',
            models.CharField(blank=True, default='', max_length=255)
        ),
        migrations.AddField(
            'publication',
            'issue',
            models.CharField(blank=True, default='', max_length=255)
        ),
        migrations.AddField(
            'publication',
            'volume',
            models.CharField(blank=True, default='', max_length=255)
        ),
        migrations.AddField(
            'publication',
            'issn',
            models.CharField(blank=True, default='', max_length=255)
        ),
        migrations.AddField(
            'publication',
            'pages',
            models.CharField(blank=True, default='', max_length=255)
        )
    ]
