# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 22:05
from __future__ import unicode_literals

from django.db import migrations

sql = \
    """
    -- Move Journal Article data into Publication table
    UPDATE core_publication SET
        journal_id = ja.tmp_journal_id,
        doi = ja.tmp_doi,
        series_text = ja.tmp_series_text,
        series_title = ja.tmp_series_title,
        series = ja.tmp_series,
        issue = ja.tmp_issue,
        volume = ja.tmp_volume,
        issn = ja.tmp_issn,
        pages = ja.tmp_pages
        FROM core_journalarticle as ja
        WHERE core_publication.id = ja.publication_ptr_id;
    """

reverse_sql = \
    """
    -- Move Publication table back into Journal model
    INSERT INTO core_journalarticle (
      publication_ptr_id,
      tmp_journal_id,
      tmp_pages,
      tmp_issn,
      tmp_volume,
      tmp_issue,
      tmp_series,
      tmp_series_title,
      tmp_series_text,
      tmp_doi)
      SELECT
        id,
        journal_id,
        pages,
        issn,
        volume,
        issue,
        series,
        series_title,
        series_text,
        doi
      FROM core_publication AS pub;
    """

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_journarticle_fields_to_publications'),
    ]

    operations = [
        migrations.RunSQL(sql=sql, reverse_sql=reverse_sql, state_operations=None)
    ]
