# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_move_journalarticle_data_to_publications'),
    ]

    operations = [
        migrations.DeleteModel('journalarticle')
    ]
