# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 21:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drop_journalarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='platform',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='model_documentation',
            field=models.ManyToManyField(blank=True, related_name='publications', to='core.ModelDocumentation'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='publications', to='core.Platform'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='resource_type',
            field=models.CharField(choices=[('JOURNAL_ARTICLE', 'Journal Article')], default='JOURNAL_ARTICLE', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='publications', to='core.Sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
