# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160708_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationauditlog',
            name='modified_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A JSON dictionary containing modified fields, if any, for the given publication', null=True),
        ),
    ]
