name: CoMSES Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo + submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: install coverage and build
      run: |
        pip3 install coveralls coverage
        ./compose 
        ./deploy.sh tag
        ./build.sh 
    - name: Run Django tests
      run: |
        docker-compose run --rm django /code/deploy/docker/test.sh
